### PR TITLE
Link AdoptOpenJDK instead of Oracle

### PR DESCRIPTION
**Pull request by Cynosphere**

### CODE REVIEW

**Comment by ThatOneCalculator** [comment]
Have you actually built and tested the program with OpenJDK?

**Comment by Cynosphere** [comment]
AdoptOpenJDK builds are meant to be backwards compatible with Oracle Java. But since you insist.

**Comment by ThatOneCalculator** [comment]
Having to type in the whole path isn't really user friendly, especially for most users who just want to download a program and run it without even touching the CLI

**Comment by ThatOneCalculator** [comment]
My take: people that don't know what they're doing should use the regular Java distribution. Ik, OpenJDK is better in most cases given its open nature but Java just works, developers that know what they're doing always have the option to use OpenJDK.

**Comment by ThatOneCalculator** [comment]
I added the mention of OpenJDK in the readme :)

**Comment by ThatOneCalculator** [comment]
@Cynosphere I also decided to make the JRE for the AUR package `jre-openjdk 15` :)

**Pull request closed without merging**
